# Generated by Django 4.0.4 on 2022-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('idauteur', models.AutoField(db_column='idAuteur', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idcategorie', models.AutoField(db_column='idCategorie', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('idcommentaire', models.AutoField(db_column='idCommentaire', primary_key=True, serialize=False)),
                ('jeux', models.CharField(blank=True, max_length=45, null=True)),
                ('joueur', models.CharField(blank=True, max_length=45, null=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commentaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('idjeux', models.AutoField(db_column='idJeux', primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=45, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=45, null=True)),
                ('photo', models.TextField()),
                ('editeur', models.CharField(blank=True, max_length=45, null=True)),
                ('auteur', models.CharField(blank=True, max_length=45, null=True)),
                ('categorie', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'jeux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('idjoueur', models.AutoField(db_column='idJoueur', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('mdp', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'joueur',
                'managed': False,
            },
        ),
    ]
