# Generated by Django 4.0.4 on 2022-06-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('idediteur', models.AutoField(db_column='idEditeur', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('date_crea', models.IntegerField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JeuxhasEditeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editeur_id', models.ForeignKey(db_column='JeuxhasEditeur_idEditeur', on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.editeur')),
                ('jeux_id', models.ForeignKey(db_column='JeuxhasEditeur_idJeux', on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.jeux')),
            ],
        ),
        migrations.DeleteModel(
            name='Auteur',
        ),
    ]
