# Generated by Django 4.0.4 on 2022-06-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_editeur_jeuxhasediteur_delete_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeuxhasediteur',
            name='editeur_id',
        ),
        migrations.RemoveField(
            model_name='jeuxhasediteur',
            name='jeux_id',
        ),
        migrations.AddField(
            model_name='jeuxhasediteur',
            name='editeur',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='ludotheque.editeur'),
        ),
        migrations.AddField(
            model_name='jeuxhasediteur',
            name='jeux',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux'),
        ),
    ]
