# Generated by Django 4.0.4 on 2022-06-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_remove_jeuxhasediteur_editeur_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeuxhasediteur',
            name='editeur',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ludotheque.editeur'),
        ),
        migrations.AlterField(
            model_name='jeuxhasediteur',
            name='jeux',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux'),
        ),
    ]
