# Generated by Django 4.0.5 on 2022-06-15 22:38

from django.db import migrations, models
import ludotheque.models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0006_alter_joueur_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.PositiveIntegerField(default=0, validators=[ludotheque.models.validate_even]),
        ),
    ]
