# Generated by Django 4.0.5 on 2022-06-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0007_alter_commentaire_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='editeur',
            field=models.ForeignKey(db_column='Jeux_idEditeur', default=1, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.editeur'),
        ),
    ]
