# Generated by Django 4.0.5 on 2022-06-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeux', models.CharField(blank=True, max_length=45, null=True)),
                ('joueur', models.CharField(blank=True, max_length=45, null=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commentaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=45, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=45, null=True)),
                ('photo', models.TextField()),
            ],
            options={
                'db_table': 'jeux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('mdp', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'joueur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JeuxhasEditeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.editeur')),
                ('jeux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux')),
            ],
        ),
    ]
