# Generated by Django 4.0.5 on 2022-06-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editeur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jeux',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joueur',
            options={},
        ),
    ]
