# Generated by Django 4.0.5 on 2022-06-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_alter_categorie_options_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='categorie',
            field=models.ForeignKey(db_column='Categorie_idCategorie', default=1, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='jeux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='date_sortie',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='titre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='mdp',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='prenom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='categorie',
            table=None,
        ),
        migrations.AlterModelTable(
            name='commentaire',
            table=None,
        ),
        migrations.AlterModelTable(
            name='editeur',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jeux',
            table=None,
        ),
        migrations.AlterModelTable(
            name='joueur',
            table=None,
        ),
    ]
