# Generated by Django 4.0.5 on 2022-06-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_jeux_categorie_alter_categorie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='jeux',
            new_name='jeu',
        ),
        migrations.RenameField(
            model_name='jeuxhasediteur',
            old_name='jeux',
            new_name='jeu',
        ),
    ]
