# Generated by Django 4.0.5 on 2022-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0004_rename_jeux_commentaire_jeu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editeur',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
