# Generated by Django 4.0.5 on 2022-06-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_remove_jeux_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='categorie',
            field=models.ForeignKey(db_column='Categorie_idCategorie', default=1, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.categorie'),
        ),
    ]
