# Generated by Django 4.0.5 on 2022-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_jeux_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='type',
            field=models.CharField(choices=[('Professionnel', 'Professionnel'), ('Particulier', 'Particulier')], default='PARTICULIER', max_length=15, verbose_name='Type'),
        ),
    ]
