# Generated by Django 4.0.5 on 2022-06-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0004_alter_joueur_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='editeur',
            field=models.ForeignKey(db_column='Jeux_idEditeur', default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.editeur'),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
